import { createContext } from 'react';

import Home from './home/index';
import About from './home/about/index';
import Head from 'next/head';

export default function Test() {
  return (
    <>
      <Head>
        <title>Marcone Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>
      <About/>

    </>
  )
}

