
//Sections
import Home from './home/landing/index';
import About from './home/about/index';
import Tolls from './home/tools/index';
import Projects from './home/projects/indext';
import Contact from './home/contact/index';

import Head from 'next/head';

export default function Test() {
  return (
    <>
      <Head>
        <title>Marcone Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#090513" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>
      <About/>
      <Tolls/>
      <Projects/>
      <Contact/>
    </>
  )
}

